export const ErrorCodes = {
  // Common Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Auth Errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',

  // Group Errors
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_ACCESS_DENIED: 'GROUP_ACCESS_DENIED',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',

  // Expense & Split Errors
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  INVALID_PAYER: 'INVALID_PAYER',
  INVALID_PARTICIPANT: 'INVALID_PARTICIPANT',
  INVALID_SPLIT_SUM: 'INVALID_SPLIT_SUM',
  INVALID_SPLIT_METHOD: 'INVALID_SPLIT_METHOD',
  INVALID_AMOUNT: 'INVALID_AMOUNT',

  // Settlement Errors
  SETTLEMENT_NOT_FOUND: 'SETTLEMENT_NOT_FOUND',
  INVALID_RECIPIENT: 'INVALID_RECIPIENT',
  SELF_SETTLEMENT_PROHIBITED: 'SELF_SETTLEMENT_PROHIBITED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
